export interface EblContainerItem {
  id?: string | number;
  sequenceNo?: number;
  qty?: number;
  packageTypeCode?: string;
  packageType?: { code?: string } | string;
  grossWeight?: number | null;
  netWeight?: number | null;
  measurementCbm?: number | null;
  description?: string;
  hsCode?: string;
}
export interface EblContainer {
  id?: string | number;
  containerNumber?: string;
  sealNumber?: string;
  containerTypeId?: string;
  containerType?: { id?: string; name?: string; code?: string };
  isHazardous?: boolean;
  items?: EblContainerItem[];
  totalQty?: number;
  quantity?: number;
  totalGrossWeight?: number;
  grossWeight?: number;
  totalNetWeight?: number;
  netWeight?: number;
  totalMeasurementCbm?: number;
  measurement?: number;
  isFallback?: boolean;
  isHeaderVisible?: boolean;
  renderItems?: Array<EblContainerItem & { displayLines?: string[] }>;
}
export interface EblParty {
  partyRole?: { code?: string; name?: string };
  partyRoleId?: string;
  companyId?: string;
  companyName?: string;
  company?: { name?: string };
  addressBookId?: string;
  addressBook?: { fullAddress?: string; address?: string; city?: string; isDefault?: boolean };
}
export interface ActiveBlData {
  id?: string;
  status?: string;
  blNumber?: string;
  job?: ActiveJobData;
  prepaid?: string;
  collect?: string;
  dateCargoReceived?: string;
  placeOfIssue?: string;
  dateOfIssue?: string;
  totalQty?: number;
  totalGrossWeight?: number;
  totalNetWeight?: number;
  totalMeasurementCbm?: number;
  renderContainers?: EblContainer[];
  jobContainers?: EblContainer[];
  blContainers?: Array<{ container?: EblContainer } & EblContainer>;
  containers?: EblContainer[];
  parties?: EblParty[];
  mainDescription?: string;
  cargoDescription?: string;
  freightTerm?: string;
  isNegotiable?: boolean;
  createdAt?: string;
  blType?: string;
  shipperReferences?: string[];
  showShipperReferencesOnBl?: boolean;
}
export interface ActiveJobData {
  id?: string;
  jobNumber?: string | null;
  pol?: string | null;
  pod?: string | null;
  polName?: string | null;
  podName?: string | null;
  vesselId?: string | null;
  etd?: string | null;
  eta?: string | null;
  tradeType?: { code?: string } | null;
  tradeTypeId?: string | null;
  cargoMovement?: { code?: string; name?: string } | null;
  cargoMovementId?: string | null;
  deliveryMovement?: { code?: string; name?: string } | null;
  deliveryMovementId?: string | null;
  customerReference?: string | null;
  preCarriageBy?: string | null;
  placeOfReceipt?: string | null;
  placeOfDelivery?: string | null;
  finalDestination?: string | null;
  vessel?: { name?: string } | null;
  voyageNumber?: string | null;
  quantity?: number | null;
  grossWeight?: number | null;
  netWeight?: number | null;
  measurement?: number | null;
  shippingMark?: string | null;
  commodity?: string | null;
  mainDescription?: string | null;
  totalBlCount?: number | null;
  jobParties?: EblParty[];
  jobContainers?: EblContainer[];
  billsOfLading?: ActiveBlData[];
  job?: ActiveJobData | null;
  hsCode?: string | null;
  blType?: string | null;
}
export interface EditFormType {
  shipperId?: string;
  shipperAddressId?: string;
  consigneeId?: string;
  consigneeAddressId?: string;
  notifyPartyId?: string;
  notifyPartyAddressId?: string;
  forwarderId?: string;
  forwarderAddressId?: string;
  isNotifySameAsConsignee?: boolean;
  mainDescription?: string;
  commodity?: string;
  hsCode?: string;
  shippingMark?: string;
  blNumber?: string;
  blType?: string;
  freightTerm?: string;
  freightPayment?: string;
  prepaidValue?: string;
  collectValue?: string;
  totalBlCount?: number;
  isNegotiable?: boolean;
  placeOfIssue?: string;
  dateOfIssue?: string;
  dateCargoReceived?: string;
  pol?: string;
  pod?: string;
  vesselId?: string;
  voyageNumber?: string;
  preCarriageBy?: string;
  placeOfReceipt?: string;
  placeOfDelivery?: string;
  finalDestination?: string;
  etd?: string;
  eta?: string;
  tradeTypeId?: string;
  cargoMovementId?: string;
  deliveryMovementId?: string;
  containers: EblContainer[];
  shipperReferences: string[];
  showShipperReferencesOnBl: boolean;
}
