export interface EblVessel {
  id?: string | number;
  vesselId?: string | null;
  transportId?: string | null;
  transportType?: string | null;
  vesselName?: string | null;
  vessel?: { name?: string | null } | null;
  plane?: { name?: string | null } | null;
  voyageNumber?: string | null;
  etd?: string | null;
  eta?: string | null;
  tsPortId?: string | null;
  tsPortName?: string | null;
  polName?: string | null;
  podName?: string | null;
  sequence?: number;
  vesselType?: string | null;
}
export interface EblContainerItem {
  id?: string | number;
  sequenceNo?: number;
  qty?: number;
  packageTypeCode?: string;
  packageType?: { code?: string } | string;
  grossWeight?: number | null;
  netWeight?: number | null;
  measurementCbm?: number | null;
  description?: string;
  hsCode?: string;
}
export interface EblContainer {
  id?: string | number;
  containerNumber?: string;
  sealNumber?: string;
  containerTypeId?: string;
  containerType?: { id?: string; name?: string; code?: string };
  vehicleNumber?: string | null;
  driverName?: string | null;
  driverContactNumber?: string | null;
  isHazardous?: boolean;
  items?: EblContainerItem[];
  totalQty?: number;
  quantity?: number;
  totalGrossWeight?: number;
  grossWeight?: number;
  totalNetWeight?: number;
  netWeight?: number;
  totalMeasurementCbm?: number;
  measurement?: number;
  isFallback?: boolean;
  isHeaderVisible?: boolean;
  renderItems?: Array<EblContainerItem & { displayLines?: string[] }>;
}
export interface EblParty {
  partyRole?: { code?: string; name?: string };
  partyRoleId?: string;
  companyId?: string;
  companyName?: string;
  company?: { name?: string };
  addressBookId?: string | null;
  addressBook?: { fullAddress?: string; address?: string; city?: string; isDefault?: boolean };
}
export interface ActiveBlData {
  id?: string;
  status?: string | { code?: string; name?: string };
  statusId?: string | null;
  blNumber?: string;
  job?: ActiveJobData;
  prepaid?: string;
  collect?: string;
  dateCargoReceived?: string;
  placeOfIssue?: string;
  dateOfIssue?: string;
  totalQty?: number;
  totalGrossWeight?: number;
  totalNetWeight?: number;
  totalMeasurementCbm?: number;
  renderContainers?: EblContainer[];
  jobContainers?: EblContainer[];
  blContainers?: Array<{ container?: EblContainer } & EblContainer>;
  containers?: EblContainer[];
  parties?: EblParty[];
  renderParties?: Record<string, { name: string; address: string }>;
  mainDescription?: string | null;
  cargoDescription?: string;
  freightTerm?: string;
  isNegotiable?: boolean;
  createdAt?: string;
  blType?: string;
  serviceContractNo?: string | null;
  shipperReferences?: string[];
  showShipperReferencesOnBl?: boolean;
  vessels?: EblVessel[];
  statusRaw?: string;
  rejectReason?: string | null;
  revisionCount?: number;
  finalizeRequestCount?: number;
}
export interface ActiveJobData {
  id?: string;
  jobNumber?: string | null;
  pol?: string | null;
  pod?: string | null;
  polName?: string | null;
  podName?: string | null;
  vesselId?: string | null;
  etd?: string | null;
  eta?: string | null;
  tsPortId?: string | null;
  tradeType?: { code?: string } | null;
  tradeTypeId?: string | null;
  cargoMovement?: { code?: string; name?: string } | null;
  cargoMovementId?: string | null;
  deliveryMovement?: { code?: string; name?: string } | null;
  deliveryMovementId?: string | null;
  customerReference?: string | null;
  preCarriageBy?: string | null;
  placeOfReceipt?: string | null;
  placeOfDelivery?: string | null;
  finalDestination?: string | null;
  vessel?: { name?: string } | null;
  plane?: { name?: string } | null;
  voyageNumber?: string | null;
  quantity?: number | string | null;
  grossWeight?: number | string | null;
  netWeight?: number | string | null;
  measurement?: number | string | null;
  shippingMark?: string | null;
  commodity?: string | null;
  mainDescription?: string | null;
  totalBlCount?: number | null;
  jobParties?: EblParty[];
  jobContainers?: EblContainer[];
  billsOfLading?: ActiveBlData[];
  job?: ActiveJobData | null;
  hsCode?: string | null;
  blType?: string | null;
  vessels?: EblVessel[];
  serviceType?: string;
  shipmentType?: string | null;
  pickupAddress?: string | null;
  deliveryAddress?: string | null;
  pickupDate?: string | null;
  deliveryDate?: string | null;
  pickupTime?: string | null;
  deliveryTime?: string | null;
  truckType?: string | null;
  status?: { code?: string; name?: string } | null;
  customer?: { id?: string; name?: string } | null;
  customerId?: string | null;
  vendor?: { id?: string; name?: string } | null;
  vendorId?: string | null;
  service?: { id?: string; name?: string } | null;
  serviceId?: string | null;
  createdAt?: string | null;
  shipperReferences?: string[] | null;
}
export interface EditFormType {
  shipperId?: string;
  shipperAddressId?: string;
  consigneeId?: string;
  consigneeAddressId?: string;
  notifyPartyId?: string;
  notifyPartyAddressId?: string;
  forwarderId?: string;
  forwarderAddressId?: string;
  customerId?: string;
  customerAddressId?: string;
  shipmentType?: string;
  isNotifySameAsConsignee?: boolean;
  mainDescription?: string;
  commodity?: string;
  hsCode?: string;
  shippingMark?: string;
  blNumber?: string;
  blType?: string;
  serviceContractNo?: string;
  freightTerm?: string;
  freightPayment?: string;
  prepaidValue?: string;
  collectValue?: string;
  totalBlCount?: number;
  isNegotiable?: boolean;
  placeOfIssue?: string;
  dateOfIssue?: string;
  dateCargoReceived?: string;
  pol?: string;
  pod?: string;
  vesselId?: string;
  voyageNumber?: string;
  preCarriageBy?: string;
  placeOfReceipt?: string;
  placeOfDelivery?: string;
  finalDestination?: string;
  etd?: string;
  eta?: string;
  tsPortId?: string;
  tradeTypeId?: string;
  cargoMovementId?: string;
  deliveryMovementId?: string;
  containers: EblContainer[];
  vessels: EblVessel[];
  shipperReferences: string[];
  showShipperReferencesOnBl: boolean;
}

export interface ProfitInvoice {
  id: string;
  issuedDate?: string | null;
  createdAt?: string | null;
  invoiceNumber: string | null;
  notes?: string | null;
  total: number | string | null;
  currency?: string | null;
  exchangeRate?: number | string | null;
  items?: { description: string | null }[] | null;
  status?: string | { code?: string; name?: string } | null;
}

export interface ProfitExpense {
  id: string;
  date?: string | null;
  createdAt?: string | null;
  vendor?: { name: string | null } | null;
  category?: { name: string | null } | null;
  description?: string | null;
  amount: number | string | null;
  currency?: string | null;
  exchangeRate?: number | string | null;
  items?: { description: string | null }[] | null;
  status?: string | { code?: string; name?: string } | null;
}

export interface ProfitJob {
  id?: string | null;
  jobNumber?: string | null;
  revenue?: number | string | null;
  cogs?: number | string | null;
  cost?: number | string | null;
  profit?: number | string | null;
  margin?: number | string | null;
  customer?: string | { name: string } | null;
  polName?: string | null;
  pol?: string | null;
  podName?: string | null;
  pod?: string | null;
  createdAt?: string | null;
  invoices?: ProfitInvoice[] | null;
  expenses?: ProfitExpense[] | null;
  vessels?: { vesselName?: string | null }[] | null;
  vessel?: { name: string } | null;
  status?: { name: string } | null;
}
