import axios, { type AxiosError } from "axios";
import type { Company } from "./useMasterData";

export type { Company as Customer };

// Type for creating a customer - code is auto-generated by backend
export type CreateCustomerInput = {
  name: string;
  email?: string;
  phone?: string;
  fullAddress?: string;
  country?: string;
  city?: string;
};

export function useCustomers() {
  const customers = useState<Company[]>("customers", () => []);
  const isLoading = useState<boolean>("customers-loading", () => false);
  const config = useRuntimeConfig();

  const api = axios.create({
    baseURL: `${config.public.apiBase}/master`,
    withCredentials: true,
  });

  type ErrorResponse = {
    message?: string;
    error?: string;
  };

  function handleApiError(error: unknown): { success: false; error: string } {
    const axiosError = error as AxiosError<ErrorResponse>;
    const apiError = axiosError.response?.data;
    const errorMessage =
      typeof apiError === "string"
        ? apiError
        : apiError?.message || apiError?.error || axiosError.message || "An error occurred";

    return { success: false, error: errorMessage };
  }

  async function fetchCustomers(): Promise<{
    success: boolean;
    data?: Company[];
    error?: string;
  }> {
    isLoading.value = true;
    try {
      const { data } = await api.get<Company[]>("/customers");
      customers.value = data || [];
      return { success: true, data: customers.value };
    } catch (error) {
      return handleApiError(error);
    } finally {
      isLoading.value = false;
    }
  }

  async function getCustomerById(
    id: string,
  ): Promise<{ success: boolean; data?: Company; error?: string }> {
    isLoading.value = true;
    try {
      const { data } = await api.get<Company>(`/customers/${id}`);
      return { success: true, data };
    } catch (error) {
      return handleApiError(error);
    } finally {
      isLoading.value = false;
    }
  }

  async function createCustomer(
    customerData: CreateCustomerInput,
  ): Promise<{ success: boolean; data?: Company; error?: string }> {
    isLoading.value = true;
    try {
      const { data } = await api.post<Company>("/customers", customerData);
      customers.value = [...customers.value, data];
      return { success: true, data };
    } catch (error) {
      return handleApiError(error);
    } finally {
      isLoading.value = false;
    }
  }

  async function updateCustomer(
    id: string,
    customerData: Partial<Omit<Company, "id">>,
  ): Promise<{ success: boolean; data?: Company; error?: string }> {
    isLoading.value = true;
    try {
      const { data } = await api.patch<Company>(`/customers/${id}`, customerData);
      customers.value = customers.value.map((c) => (c.id === id ? { ...c, ...data } : c));
      return { success: true, data };
    } catch (error) {
      return handleApiError(error);
    } finally {
      isLoading.value = false;
    }
  }

  async function deleteCustomer(id: string): Promise<{ success: boolean; error?: string }> {
    isLoading.value = true;
    try {
      await api.delete(`/customers/${id}`);
      customers.value = customers.value.filter((c) => c.id !== id);
      return { success: true };
    } catch (error) {
      return handleApiError(error);
    } finally {
      isLoading.value = false;
    }
  }

  return {
    customers,
    isLoading,
    fetchCustomers,
    getCustomerById,
    createCustomer,
    updateCustomer,
    deleteCustomer,
  };
}
